create table public.notifications (
  notif_id bigint generated by default as identity not null,
  notif_type public.notification_type null,
  created_at timestamp with time zone not null default now(),
  user_auth_id uuid null,
  constraint notifications_pkey primary key (notif_id),
  constraint notifications_user_auth_id_fkey foreign KEY (user_auth_id) references users (auth_id)
) TABLESPACE pg_default;